services:
  server:
    container_name: zeedzad
    user: ${UID}:${GID}
    expose:
      - 8088
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    mem_limit: 256m
    env_file:
      - zerver.env
    networks:
      - internal
      - public

networks:
  public:
    name: main
    driver: bridge
    external: true
  internal:
    driver: bridge
