[tools]
bun = "1.3"
go = "1.25"

[tasks.swag]
run = "swag init -d pkg -g server/server.go -o pkg/docs --ot go"

[tasks.build-server]
dir = "{{ config_root }}/pkg"
sources = ["**/*.go"]
run = "go build -ldflags=\"-s -w\" -v -o dist/app"

[tasks.run-server]
depends = ["build-server"]
dir = "{{ config_root }}/pkg"
run = "dist/app"
sources = ["**/*.go"]
description = "Run the Go server"
