//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Games struct {
	ID        *string   `sql:"primary_key" json:"id"`
	AppID     string    `json:"app_id"`
	Name      string    `json:"name"`
	Icon      *string   `json:"icon"`
	Logo      *string   `json:"logo"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
