//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Videos struct {
	ID           *string   `sql:"primary_key" json:"id"`
	YoutubeID    string    `json:"youtube_id"`
	Title        string    `json:"title"`
	Description  *string   `json:"description"`
	Thumbnail    *string   `json:"thumbnail"`
	PublishedAt  time.Time `json:"published_at"`
	ChannelID    string    `json:"channel_id"`
	ChannelTitle *string   `json:"channel_title"`
	GameID       *string   `json:"game_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
