//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Videos struct {
	ID          *string   `sql:"primary_key" json:"id"`
	Title       string    `json:"title"`
	Thumbnail   *string   `json:"thumbnail"`
	PublishedAt time.Time `json:"published_at"`
	GameID      *int32    `json:"game_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
